# src/story_engines/classic_narrative/agents/enhanced_scene_planner.py

import json
import re
import gc
import asyncio
import traceback
import textstat
from typing import List, Optional, Callable, Any, Tuple, Dict
from pydantic import BaseModel, Field
from dataclasses import dataclass
from src.llm_client.llm_client import writer_client
from langgraph.graph import StateGraph, END
from src.utilities.story_helpers import StoryHelpers
from langchain_core.output_parsers import PydanticOutputParser

# Global shared instance
CLASSIC_SCENE_PLANNER_SERVICE = None


# ============================================================================
# PYDANTIC MODELS
# ============================================================================

class ParagraphOutline(BaseModel):
    """Detailed outline for a single paragraph"""
    paragraph_number: int = Field(description="Sequential paragraph number")
    objective: str = Field(description="What this paragraph accomplishes")
    opening_sentence: str = Field(description="First sentence written out")
    key_events: List[str] = Field(description="2-3 specific things that happen")
    sensory_details: List[str] = Field(description="Specific sensory elements to include")
    dialogue_present: bool = Field(description="Does this paragraph contain dialogue?")
    dialogue_agents: Optional[List[str]] = Field(default=None, description="Who speaks if dialogue present")
    emotional_note: str = Field(description="Emotional tone/shift in this paragraph")
    transition_to_next: str = Field(description="How to flow into next paragraph")
    target_word_count: int = Field(description="Target words for this paragraph", ge=60, le=200)


class ProseOutline(BaseModel):
    """Complete prose outline for a scene"""
    scene_id: int
    total_paragraphs: int = Field(description="Number of paragraphs in scene")
    paragraphs: List[ParagraphOutline] = Field(description="Detailed paragraph-by-paragraph plan")
    opening_image_execution: str = Field(description="Exactly how to open the scene")
    closing_image_execution: str = Field(description="Exactly how to close the scene")
    pacing_strategy: str = Field(description="Concrete pacing approach")
    voice_notes: Dict[str, str] = Field(description="Agent name -> specific voice reminders")


class ParagraphOutput(BaseModel):
    """Single paragraph generated by writer"""
    paragraph_text: str = Field(description="The prose paragraph (60-200 words)")
    word_count: int = Field(description="Actual word count")
    next_action: str = Field(description="'Continue' or 'End'")


class AgeAppropriateReport(BaseModel):
    """Content validation report"""
    is_appropriate: bool = Field(description="Whether content passes age filter")
    readability_grade: float = Field(description="Flesch-Kincaid grade level")
    target_grade: float = Field(description="Target grade level for age")
    issues: List[str] = Field(default_factory=list, description="Problems detected")
    warnings: List[str] = Field(default_factory=list, description="Potential concerns")
    recommendations: List[str] = Field(default_factory=list, description="Suggested adjustments")


class SceneMemory(BaseModel):
    DirectorInstructions: Any = Field(description="Director's instructions for this scene.")
    prose_outline: Optional[ProseOutline] = Field(default=None, description="Detailed prose outline")
    scene_so_far: str = Field(default="", description="Accumulated text of the scene.")
    scene_cluster: List = Field(default=[], description="Scene text, questions, and user choices as dicts.")
    word_count: int = Field(..., description="Word count of the scene.")
    story_id: Optional[str] = Field(default="", description="Story ID for this scene.")
    current_paragraph_number: int = Field(default=1, description="Which paragraph we're writing")


class SceneState(BaseModel):
    scene_memory: Optional[SceneMemory] = None
    next_node: Optional[str] = None
    user_context_id: Optional[str] = Field(default=None, description="User ID for this scene")
    user_age: int = Field(default=13, description="Target audience age")
    iteration_count: int = 0
    scene_chunk_callback: Optional[Callable] = Field(default=None, description="Callback for frontend updates")
    error_type: Optional[str] = None
    error_message: Optional[str] = None
    fatal: bool = False
    llm_temp: float = Field(default=0.7, description="Temperature for LLM")
    model: str = Field(default="None", description="Model name for LLM")
    token_usage: dict = Field(default_factory=lambda: {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0})
    target_length: int = Field(default=500, description="Target length for the story")
    scene_target_length: int = Field(default=500, description="Target length for this scene")

    class Config:
        extra = "allow"


@dataclass
class UserSceneContext:
    user_id: str
    story_id: str
    director_instructions: Any
    scene_state: SceneState
    scene_memory: SceneMemory
    scene_chunk_callback: Callable

    @classmethod
    def create_for_user(cls, user_id: str, story_id: str, director_instructions: str, 
                       scene_chunk_callback: Callable, llm_temp: float = 0.7, model: str = "None",
                       token_usage: dict = None, target_length: int = 500, 
                       scene_target_length: int = 500, user_age: int = 13):
        token_usage = token_usage or {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}
        
        scene_memory = SceneMemory(
            DirectorInstructions=director_instructions.strip(),
            scene_so_far="",
            story_id=story_id,
            word_count=0,
            current_paragraph_number=1
        )

        scene_state = SceneState(
            scene_memory=scene_memory,
            next_node=None,
            user_context_id=user_id,
            user_age=user_age,
            scene_chunk_callback=scene_chunk_callback,
            llm_temp=llm_temp,
            model=model,
            token_usage=token_usage,
            target_length=target_length,
            scene_target_length=scene_target_length
        )

        return cls(
            user_id=user_id,
            story_id=story_id,
            director_instructions=director_instructions,
            scene_state=scene_state,
            scene_memory=scene_memory,
            scene_chunk_callback=scene_chunk_callback
        )


# ============================================================================
# AGE APPROPRIATE VALIDATOR
# ============================================================================

class AgeAppropriateValidator:
    """Validates content appropriateness for target age using readability metrics"""
    
    # Age to Flesch-Kincaid grade level mapping
    AGE_TO_GRADE = {
        8: 3.0,   # 3rd grade
        9: 4.0,   # 4th grade
        10: 5.0,  # 5th grade
        11: 6.0,  # 6th grade
        12: 7.0,  # 7th grade
        13: 8.0,  # 8th grade
        14: 9.0,  # 9th grade
        15: 10.0, # 10th grade
        16: 11.0, # 11th grade
        17: 12.0, # 12th grade
        18: 13.0  # College level
    }
    
    # Content keywords to flag by age
    SENSITIVE_KEYWORDS = {
        "violence": ["blood", "gore", "mutilated", "dismember", "torture", "slaughter"],
        "mature_themes": ["sexual", "seductive", "arousal", "explicit"],
        "strong_language": ["damn", "hell", "bastard", "bitch"],  # Mild profanity
        "dark_themes": ["suicide", "self-harm", "overdose", "rape"]
    }
    
    AGE_RESTRICTIONS = {
        8: {"block": ["violence", "mature_themes", "strong_language", "dark_themes"]},
        9: {"block": ["violence", "mature_themes", "strong_language", "dark_themes"]},
        10: {"block": ["violence", "mature_themes", "strong_language", "dark_themes"]},
        11: {"block": ["mature_themes", "strong_language", "dark_themes"], "warn": ["violence"]},
        12: {"block": ["mature_themes", "dark_themes"], "warn": ["violence", "strong_language"]},
        13: {"block": ["mature_themes", "dark_themes"], "warn": ["violence", "strong_language"]},
        14: {"block": ["mature_themes"], "warn": ["dark_themes", "violence"]},
        15: {"warn": ["mature_themes", "dark_themes"]},
        16: {"warn": ["mature_themes", "dark_themes"]},
        17: {"warn": ["mature_themes"]},
        18: {}  # No restrictions
    }
    
    @staticmethod
    def get_target_grade(age: int) -> float:
        """Get target Flesch-Kincaid grade for age"""
        return AgeAppropriateValidator.AGE_TO_GRADE.get(age, 8.0)
    
    @staticmethod
    def calculate_readability(text: str) -> Dict[str, float]:
        """Calculate multiple readability metrics"""
        if len(text.strip()) < 100:  # Too short for reliable metrics
            return {
                "flesch_kincaid_grade": 5.0,
                "flesch_reading_ease": 80.0,
                "gunning_fog": 8.0
            }
        
        try:
            return {
                "flesch_kincaid_grade": textstat.flesch_kincaid_grade(text),
                "flesch_reading_ease": textstat.flesch_reading_ease(text),
                "gunning_fog": textstat.gunning_fog(text)
            }
        except Exception as e:
            print(f"⚠️ Readability calculation error: {e}")
            return {
                "flesch_kincaid_grade": 8.0,
                "flesch_reading_ease": 70.0,
                "gunning_fog": 10.0
            }
    
    @staticmethod
    def detect_sensitive_content(text: str, age: int) -> Dict[str, List[str]]:
        """Detect sensitive content based on age restrictions"""
        text_lower = text.lower()
        detected = {"blocked": [], "warnings": []}
        
        restrictions = AgeAppropriateValidator.AGE_RESTRICTIONS.get(age, {})
        blocked_categories = restrictions.get("block", [])
        warn_categories = restrictions.get("warn", [])
        
        for category, keywords in AgeAppropriateValidator.SENSITIVE_KEYWORDS.items():
            found_keywords = [kw for kw in keywords if kw in text_lower]
            
            if found_keywords:
                if category in blocked_categories:
                    detected["blocked"].append(f"{category}: {', '.join(found_keywords)}")
                elif category in warn_categories:
                    detected["warnings"].append(f"{category}: {', '.join(found_keywords)}")
        
        return detected
    
    @staticmethod
    def validate_content(text: str, target_age: int) -> AgeAppropriateReport:
        """Comprehensive content validation"""
        target_grade = AgeAppropriateValidator.get_target_grade(target_age)
        readability = AgeAppropriateValidator.calculate_readability(text)
        sensitive = AgeAppropriateValidator.detect_sensitive_content(text, target_age)
        
        actual_grade = readability["flesch_kincaid_grade"]
        grade_diff = actual_grade - target_grade
        
        issues = []
        warnings = []
        recommendations = []
        
        # Check readability
        if grade_diff > 2.0:
            issues.append(f"Text too complex: grade {actual_grade:.1f} vs target {target_grade:.1f}")
            recommendations.append("Simplify sentence structure and vocabulary")
        elif grade_diff > 1.0:
            warnings.append(f"Text slightly complex: grade {actual_grade:.1f} vs target {target_grade:.1f}")
            recommendations.append("Consider shorter sentences")
        
        # Check sensitive content
        if sensitive["blocked"]:
            issues.extend(sensitive["blocked"])
            recommendations.append("Remove or rephrase flagged content for age group")
        
        if sensitive["warnings"]:
            warnings.extend(sensitive["warnings"])
            recommendations.append("Review flagged content for age-appropriateness")
        
        # Check sentence length for younger audiences
        if target_age <= 12:
            avg_sentence_length = textstat.avg_sentence_length(text)
            if avg_sentence_length > 20:
                warnings.append(f"Average sentence length {avg_sentence_length:.1f} may be too long")
                recommendations.append("Break long sentences into shorter ones")
        
        is_appropriate = len(issues) == 0 and len(sensitive["blocked"]) == 0
        
        return AgeAppropriateReport(
            is_appropriate=is_appropriate,
            readability_grade=actual_grade,
            target_grade=target_grade,
            issues=issues,
            warnings=warnings,
            recommendations=recommendations
        )


# ============================================================================
# SCENE OUTLINER AGENT
# ============================================================================

class SceneOutlinerAgent:
    """Converts Director's abstract directives into concrete prose outline"""
    
    def __init__(self):
        self.parser = PydanticOutputParser(pydantic_object=ProseOutline)
    
    async def create_prose_outline(
        self,
        directive: Dict[str, Any],
        scene_target_length: int,
        llm_temp: float,
        model: str,
        token_usage: Dict[str, int]
    ) -> Tuple[ProseOutline, Dict[str, int]]:
        """Convert Director's directive into paragraph-by-paragraph outline"""
        
        # Calculate paragraph breakdown
        avg_paragraph_length = 120  # Target average
        estimated_paragraphs = max(3, min(12, scene_target_length // avg_paragraph_length))
        
        system_prompt = f"""You are a Scene Outliner converting a Director's vision into a concrete prose outline.

The Director has provided abstract creative guidance. Your job is to translate this into a SPECIFIC paragraph-by-paragraph plan that a writer can execute.

For each paragraph:
1. Define a clear objective (what story purpose it serves)
2. Write out the opening sentence exactly
3. List 2-3 specific events/actions that happen
4. Specify sensory details to include (with exact descriptions)
5. Note if dialogue is present and who speaks
6. Describe emotional tone/shift
7. Plan the transition to next paragraph

Be CONCRETE. Instead of "show character's fear", write "Sarah's hands tremble as she reaches for the doorknob, sweat beading on her forehead."

Target: {estimated_paragraphs} paragraphs totaling ~{scene_target_length} words

{self.parser.get_format_instructions()}"""

        human_prompt = f"""Create a detailed prose outline from this directive:

DIRECTOR'S VISION:
Author Intent: {directive.get('author_intent', 'N/A')}
Opening Image: {directive.get('opening_image', '')}
Scene Blocking: {directive.get('scene_blocking', '')}
Pacing: {directive.get('pacing_direction', '')}
Dialogue Guidance: {directive.get('dialogue_guidance', '')}
Sensory Palette: {', '.join(directive.get('sensory_palette', []))}
Emotional Camera: {directive.get('emotional_camera', '')}
Rhythm: {directive.get('scene_rhythm', '')}
Must Include: {', '.join(directive.get('key_details_to_include', []))}
Closing Image: {directive.get('closing_image', '')}
Style: {directive.get('style_adjustments', '')}

Generate {estimated_paragraphs} paragraph outlines with specific, executable instructions."""

        try:
            response, tokens = await writer_client(
                system_prompt=system_prompt,
                human_prompt=human_prompt,
                llm_temp=llm_temp,
                model=model
            )
            
            token_usage["prompt_tokens"] += tokens["prompt_tokens"]
            token_usage["completion_tokens"] += tokens["completion_tokens"]
            token_usage["total_tokens"] += tokens["total_tokens"]
            
            clean_resp = StoryHelpers._extract_content(response)
            clean_resp = StoryHelpers._strip_code_fences(clean_resp)
            
            json_data = await StoryHelpers.load_json_with_retry(clean_resp, self.parser)
            outline = self.parser.parse(json_data)
            
            print(f"✅ Prose outline created: {outline.total_paragraphs} paragraphs planned")
            return outline, token_usage
            
        except Exception as e:
            print(f"❌ Scene Outliner failed: {e}")
            traceback.print_exc()
            raise


# ============================================================================
# CLASSIC SCENE PLANNER SERVICE
# ============================================================================

class ScenePlannerService:
    def __init__(self):
        self.paragraph_parser = PydanticOutputParser(pydantic_object=ParagraphOutput)
        self.outliner = SceneOutlinerAgent()
        self.validator = AgeAppropriateValidator()
        
        # Build paragraph writer system prompt
        self.paragraph_writer_system = """You are a Paragraph Writer executing a detailed prose outline.

CRITICAL RULES:
1. Write EXACTLY ONE paragraph (60-200 words)
2. Follow the outline's objective precisely
3. Use the provided opening sentence or very similar
4. Include all specified sensory details and events
5. Maintain consistent character voices
6. Respect the emotional tone
7. Create smooth transition as specified

OUTPUT REQUIREMENTS:
- Valid JSON only
- 'paragraph_text': The prose paragraph
- 'word_count': Actual word count
- 'next_action': "Continue" or "End"

Write beautiful, engaging prose that brings the outline to life."""

        # Build graph
        self.graph = StateGraph(SceneState)
        self.graph.add_node("Initializer", self._initializer)
        self.graph.add_node("SceneOutliner", self._scene_outliner)
        self.graph.add_node("ParagraphWriter", self._paragraph_writer)
        self.graph.add_node("ContentValidator", self._content_validator)
        
        self.graph.set_entry_point("Initializer")
        self.graph.add_edge("Initializer", "SceneOutliner")
        self.graph.add_edge("SceneOutliner", "ParagraphWriter")
        
        def writer_decider(state: SceneState):
            if getattr(state, "fatal", False) or getattr(state, "next_node", None) == "FATAL_ERROR":
                return "FATAL_ERROR"
            
            next_action = getattr(state, "next_node", "End")
            if next_action == "Continue":
                return "ParagraphWriter"
            elif next_action == "Validate":
                return "ContentValidator"
            return "END"
        
        self.graph.add_conditional_edges(
            "ParagraphWriter",
            writer_decider,
            {
                "ParagraphWriter": "ParagraphWriter",
                "ContentValidator": "ContentValidator",
                "END": END,
                "FATAL_ERROR": END
            }
        )
        
        def validator_decider(state: SceneState):
            if getattr(state, "fatal", False):
                return "FATAL_ERROR"
            return "END"
        
        self.graph.add_conditional_edges(
            "ContentValidator",
            validator_decider,
            {
                "END": END,
                "FATAL_ERROR": END
            }
        )
        
        self.compiled = self.graph.compile()
    
    def _handle_fatal_error(self, state: SceneState, error: Exception, stage: str) -> SceneState:
        state.fatal = True
        state.next_node = "FATAL_ERROR"
        state.error_type = stage
        state.error_message = f"{type(error).__name__}: {str(error)}"
        print(f"❌ [FATAL] {stage} failed – {state.error_message}")
        traceback.print_exc()
        return state
    
    async def run_scene(self, user_context: UserSceneContext, stop_event: asyncio.Event | None = None) -> Tuple[str, list, str, dict]:
        print(f"🎭 Starting enhanced run_scene for {user_context.user_id}/{user_context.story_id}")
        
        try:
            user_context.scene_state.user_context_id = user_context.user_id
        except Exception as e:
            print(f"❌ Failed to set user_context_id: {e}")
            traceback.print_exc()
            return "", [], f"EXCEPTION: {type(e).__name__}: {e}", user_context.scene_state.token_usage
        
        try:
            task = asyncio.create_task(
                self.compiled.ainvoke(user_context.scene_state, {"recursion_limit": 30, "stop_event": stop_event})
            )
            
            while not task.done():
                if stop_event and stop_event.is_set():
                    print("🛑 Stop event received – cancelling SceneGraph task...")
                    task.cancel()
                    try:
                        await task
                    except asyncio.CancelledError:
                        print("✅ SceneGraph task cancelled cleanly")
                    return "", [], "CANCELLED", user_context.scene_state.token_usage
                await asyncio.sleep(0.2)
            
            result = await task
            if not isinstance(result, dict):
                user_context.scene_state = result
            else:
                user_context.scene_state = SceneState(**result)
            
            next_node = getattr(result, "next_node", None) if not isinstance(result, dict) else result.get("next_node")
            error_message = getattr(result, "error_message", None) if not isinstance(result, dict) else result.get("error_message")
            scene_memory = getattr(result, "scene_memory", None) if not isinstance(result, dict) else result.get("scene_memory")
            
            if getattr(result, "fatal", False) or next_node == "FATAL_ERROR":
                fatal_msg = error_message or "Unknown fatal error"
                print(f"❌ Scene aborted due to fatal error: {fatal_msg}")
                return "", [], f"FATAL: {fatal_msg}", user_context.scene_state.token_usage
            
            if scene_memory is None:
                print("⚠️ Warning: LangGraph returned with no scene_memory.")
                return "", [], "EXCEPTION: No scene_memory returned", user_context.scene_state.token_usage
            
            scene_so_far = getattr(scene_memory, "scene_so_far", "") if not isinstance(scene_memory, dict) else scene_memory.get("scene_so_far", "")
            scene_cluster = getattr(scene_memory, "scene_cluster", []) if not isinstance(scene_memory, dict) else scene_memory.get("scene_cluster", [])
            
            print("✅ Scene completed normally")
            return scene_so_far, scene_cluster, "SUCCESS", user_context.scene_state.token_usage
        
        except asyncio.CancelledError:
            print("🛑 SceneGraph CancelledError caught")
            return "", [], "CANCELLED", user_context.scene_state.token_usage
        except Exception as e:
            print(f"❌ ERROR in run_scene: {e}")
            traceback.print_exc()
            return "", [], f"EXCEPTION: {type(e).__name__}: {e}", user_context.scene_state.token_usage
        finally:
            print("🎭 SceneGraph stopped gracefully")
            gc.collect()
    
    def _initializer(self, state: SceneState) -> SceneState:
        print(f"🔧 Initializer node for user_context_id={state.user_context_id}, age={state.user_age}")
        if getattr(state, "fatal", False):
            return state
        state.next_node = "SceneOutliner"
        return state
    
    async def _scene_outliner(self, state: SceneState) -> SceneState:
        """Generate detailed prose outline from Director's directive"""
        print(f"📋 Scene Outliner generating prose outline...")
        
        if getattr(state, "fatal", False):
            return state
        
        scene_memory: SceneMemory = state.scene_memory
        
        try:
            directive = json.loads(scene_memory.DirectorInstructions)
            
            outline, token_usage = await self.outliner.create_prose_outline(
                directive=directive,
                scene_target_length=state.scene_target_length,
                llm_temp=state.llm_temp,
                model=state.model,
                token_usage=state.token_usage
            )
            
            scene_memory.prose_outline = outline
            state.scene_memory = scene_memory
            state.token_usage = token_usage
            state.next_node = "ParagraphWriter"
            
            print(f"✅ Outline complete: {outline.total_paragraphs} paragraphs planned")
            
            return state
            
        except Exception as e:
            return self._handle_fatal_error(state, e, "SceneOutliner")
    
    async def _paragraph_writer(self, state: SceneState) -> SceneState:
        """Write one paragraph at a time following the outline"""
        print(f"✍️ Writing paragraph {state.scene_memory.current_paragraph_number}")
        
        if getattr(state, "fatal", False):
            return state
        
        scene_memory: SceneMemory = state.scene_memory
        prose_outline: ProseOutline = scene_memory.prose_outline
        
        # Check if we're done
        if scene_memory.current_paragraph_number > prose_outline.total_paragraphs:
            print(f"✅ All {prose_outline.total_paragraphs} paragraphs written")
            state.next_node = "Validate"
            return state
        
        # Circuit breaker
        if state.iteration_count > 20:
            print(f"🛑 FORCE END: Exceeded max iterations")
            state.next_node = "Validate"
            return state
        
        # Get current paragraph outline
        current_para = prose_outline.paragraphs[scene_memory.current_paragraph_number - 1]
        
        # Build context-aware prompt
        human_prompt = f"""Write paragraph {scene_memory.current_paragraph_number} of {prose_outline.total_paragraphs}.

PARAGRAPH OUTLINE:
Objective: {current_para.objective}
Opening sentence: {current_para.opening_sentence}
Key events: {', '.join(current_para.key_events)}
Sensory details to include: {', '.join(current_para.sensory_details)}
Dialogue: {"Yes - " + ', '.join(current_para.dialogue_agents) if current_para.dialogue_present else "No"}
Emotional tone: {current_para.emotional_note}
Transition: {current_para.transition_to_next}
Target words: {current_para.target_word_count}

PREVIOUS TEXT:
{scene_memory.scene_so_far[-500:] if scene_memory.scene_so_far else "[Scene starting now]"}

VOICE REMINDERS:
{json.dumps(prose_outline.voice_notes, indent=2)}

Write this paragraph following the outline exactly. Output valid JSON only:
{self.paragraph_parser.get_format_instructions()}"""
        
        try:
            response, tokens = await writer_client(
                system_prompt=self.paragraph_writer_system,
                human_prompt=human_prompt,
                llm_temp=state.llm_temp,
                model=state.model
            )
            
            state.token_usage["prompt_tokens"] += tokens["prompt_tokens"]
            state.token_usage["completion_tokens"] += tokens["completion_tokens"]
            state.token_usage["total_tokens"] += tokens["total_tokens"]
            
            clean_resp = StoryHelpers._extract_content(response)
            clean_resp = StoryHelpers._strip_code_fences(clean_resp)
            
            try:
                parsed = self.paragraph_parser.parse(clean_resp)
                paragraph_text = parsed.paragraph_text
                word_count = parsed.word_count
            except Exception as e:
                print(f"⚠️ Parser failed, attempting JSON fix: {e}")
                fixed_json = await StoryHelpers._json_fixer(clean_resp)
                try:
                    parsed = self.paragraph_parser.parse(fixed_json)
                    paragraph_text = parsed.paragraph_text
                    word_count = parsed.word_count
                except Exception as repair_e:
                    print(f"❌ JSON fixer failed: {repair_e}")
                    match = re.search(r'"paragraph_text"\s*:\s*"([^"]*)"', clean_resp)
                    paragraph_text = match.group(1) if match else ""
                    word_count = StoryHelpers._count_words_split(paragraph_text)
            
            # Update scene memory
            actual_word_count = StoryHelpers._count_words_split(paragraph_text)
            scene_memory.word_count += actual_word_count
            scene_memory.scene_cluster.append({
                "type": "text",
                "scene_text": paragraph_text,
                "word_count": actual_word_count,
                "paragraph_number": scene_memory.current_paragraph_number
            })
            scene_memory.scene_so_far += ("\n\n" + paragraph_text)
            
            print(f"📝 Paragraph {scene_memory.current_paragraph_number}: {actual_word_count} words | Total: {scene_memory.word_count}/{state.scene_target_length}")
            
            # Send to frontend
            if state.scene_chunk_callback:
                try:
                    state.scene_chunk_callback({
                        "type": "text",
                        "scene_text": paragraph_text
                    })
                    state.scene_chunk_callback({
                        "type": "status",
                        "word_count": actual_word_count,
                        "total_word_count": scene_memory.word_count,
                        "target_word_count": state.scene_target_length,
                        "completion_percentage": int((scene_memory.word_count / state.scene_target_length) * 100),
                        "paragraph_number": scene_memory.current_paragraph_number,
                        "total_paragraphs": prose_outline.total_paragraphs
                    })
                except Exception as e:
                    print(f"❌ Callback failed: {e}")
            
            # Move to next paragraph
            scene_memory.current_paragraph_number += 1
            state.scene_memory = scene_memory
            state.iteration_count += 1
            
            # Decide next action
            if scene_memory.current_paragraph_number > prose_outline.total_paragraphs:
                state.next_node = "Validate"
            else:
                state.next_node = "Continue"
            
            del response, clean_resp, tokens
            gc.collect()
            return state
            
        except asyncio.TimeoutError as e:
            return self._handle_fatal_error(state, e, "ParagraphWriter Timeout")
        except Exception as e:
            return self._handle_fatal_error(state, e, "ParagraphWriter")
    
    async def _content_validator(self, state: SceneState) -> SceneState:
        """Validate final scene content for age-appropriateness"""
        print(f"🔍 Validating content for age {state.user_age}...")
        
        if getattr(state, "fatal", False):
            return state
        
        scene_memory: SceneMemory = state.scene_memory
        full_scene_text = scene_memory.scene_so_far
        
        try:
            # Run validation
            report = self.validator.validate_content(full_scene_text, state.user_age)
            
            print(f"📊 Readability: {report.readability_grade:.1f} (target: {report.target_grade:.1f})")
            
            if report.issues:
                print(f"⚠️ Content Issues Found:")
                for issue in report.issues:
                    print(f"   - {issue}")
            
            if report.warnings:
                print(f"⚠️ Content Warnings:")
                for warning in report.warnings:
                    print(f"   - {warning}")
            
            if report.recommendations:
                print(f"💡 Recommendations:")
                for rec in report.recommendations:
                    print(f"   - {rec}")
            
            # Add validation report to scene cluster
            scene_memory.scene_cluster.append({
                "type": "validation_report",
                "is_appropriate": report.is_appropriate,
                "readability_grade": report.readability_grade,
                "target_grade": report.target_grade,
                "issues": report.issues,
                "warnings": report.warnings,
                "recommendations": report.recommendations
            })
            
            # Send validation to frontend
            if state.scene_chunk_callback:
                try:
                    state.scene_chunk_callback({
                        "type": "validation",
                        "is_appropriate": report.is_appropriate,
                        "readability_grade": round(report.readability_grade, 1),
                        "target_grade": round(report.target_grade, 1),
                        "issues_count": len(report.issues),
                        "warnings_count": len(report.warnings)
                    })
                except Exception as e:
                    print(f"❌ Validation callback failed: {e}")
            
            state.scene_memory = scene_memory
            
            if report.is_appropriate:
                print("✅ Content validated successfully")
            else:
                print("⚠️ Content has issues but proceeding (manual review recommended)")
            
            state.next_node = "End"
            return state
            
        except Exception as e:
            print(f"⚠️ Content validation failed: {e}")
            traceback.print_exc()
            # Don't fail the whole scene for validation errors
            state.next_node = "End"
            return state


# ============================================================================
# GLOBAL INSTANCE
# ============================================================================

def initialize_classic_scene_planner():
    """Initialize the global enhanced scene planner service"""
    global CLASSIC_SCENE_PLANNER_SERVICE
    if CLASSIC_SCENE_PLANNER_SERVICE is None:
        CLASSIC_SCENE_PLANNER_SERVICE = ScenePlannerService()
        print("✅ Enhanced Scene Planner Service initialized")
    return CLASSIC_SCENE_PLANNER_SERVICE


# Initialize on import
CLASSIC_SCENE_PLANNER_SERVICE = initialize_classic_scene_planner()


# ============================================================================
# USAGE EXAMPLE
# ============================================================================

"""
# How to use in director_agent_classic.py:

from src.story_engines.classic_narrative.agents.enhanced_scene_planner import (
    ENHANCED_SCENE_PLANNER_SERVICE,
    UserSceneContext
)

# In generate_scenes_node:
user_context = UserSceneContext.create_for_user(
    user_id=self.memory.user_id,
    story_id=self.memory.story_id,
    director_instructions=director_instructions,
    scene_chunk_callback=self.scene_chunk_callback,
    llm_temp=self.llm_temp,
    model=self.model,
    token_usage=self.writer_token_usage,
    target_length=self.target_length,
    scene_target_length=directive.word_count,
    user_age=progress.get('user_age', 13)  # Add this to your progress storage
)

scene_text, scene_cluster, status, writer_tokens = await ENHANCED_SCENE_PLANNER_SERVICE.run_scene(
    user_context=user_context,
    stop_event=self.stop_event
)

# The scene_cluster will now include validation reports:
# {
#     "type": "validation_report",
#     "is_appropriate": True,
#     "readability_grade": 7.8,
#     "target_grade": 8.0,
#     "issues": [],
#     "warnings": ["Text slightly complex..."],
#     "recommendations": ["Consider shorter sentences"]
# }
"""